### PR TITLE
feat: Index page revamp

### PR DESCRIPTION
**Pull request by dan-lee**
Following up on the request list overview page, I also reworked the index page.
I didn't change it as drastically, but I cleaned up the font sizes a bit and rendered the list of recent bins next to the form to save some space.

I also added `Fira Code` as the mono font as the default one looked a bit bland.

### CODE REVIEW

**Comment by ntotten** [comment]
margin on text 
image

**Comment by AdrianMachado** [comment]
I know this was a previous PR, but could you add a "successfully copied" state when you click this button 
image

**Comment by AdrianMachado** [comment]
Also, not necessary for this PR but some cool things would be:
1. Typeahead on the header name with common headers. Thunder Client does this well 
image
2. Maybe we should use Monaco Editor on the body - not sure if its too heavy wait but manually balancing parenthesis is annoying

**Comment by dan-lee** [comment]
@ntotten great catch, didn't test it with no bins 😅

@AdrianMachado:

- Oh yeah, well spotted. I absolutely forgot the feedback on the copy button. Will add that on a separate PR!
- I love the idea with the typeahead, will also address this in a separate PR!
- `monaco-editor` apparently adds ~18 kb min + gzip [according to bundlephobia](https://bundlephobia.com/package/monaco-editor@0.45.0) which wouldn't be too bad IMHO. I'll need to play around if that is actually the true final size.

**Pull request merged**
